# Generated by Django 6.0 on 2026-01-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_post_image_postmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='posts/thumbnails/'),
        ),
    ]
