# Generated by Django 6.0 on 2026-01-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro',
            field=models.TextField(blank=True, help_text='User self-introduction', null=True),
        ),
    ]
